### ISSUE TITLE
/org/ のレスポンス

### ISSUE THREAD

**Issue by eggplants** [tsukuba-shinkan/shinkan-next#6]
たぶん、401の時の処理が必要です。

<https://github.com/tsukuba-shinkan/shinkan-next/blob/main/utils/orgPageIds.ts>に...

## ある: 

- https://www.stb.tsukuba.ac.jp/~shinkan-web/org/271/ #=> 200 OK, 正常
  - <https://www.stb.tsukuba.ac.jp/~shinkan-web/orgadmin/?rest_route=/wp/v2/pages/271>

```json
{
  ...完璧なデータ...
}
```

- https://www.stb.tsukuba.ac.jp/~shinkan-web/org/404/ #=> 200 OK,「読み込み中...」
  - <https://www.stb.tsukuba.ac.jp/~shinkan-web/orgadmin/?rest_route=/wp/v2/pages/404>

```json
{
  "code": "rest_forbidden",
  "message": "その操作を実行する権限がありません。",
  "data": {
    "status": 401
  }
}
```

## ない:

- https://www.stb.tsukuba.ac.jp/~shinkan-web/org/407/ #=> 404 Not Found
  - <https://www.stb.tsukuba.ac.jp/~shinkan-web/orgadmin/?rest_route=/wp/v2/pages/407>

```json
{
  "code": "rest_post_invalid_id",
  "message": "無効な投稿 ID です。",
  "data": {
    "status": 404
  }
}
```

**Comment by yuki-js** [comment]
ご報告ありがとうございます。
アドレスバーに直接打ち込まない限りアクセスされないと思ったので、意図的にエラーハンドリングをサボりました

また、リプでいただいた408番は、ActionsでSSGされた時点の添付画像と最新のWPの添付画像が違ったことが原因でReactのHook構造が変化したためでした。現在修正しております。Reactは難しい。

**Comment by eggplants** [comment]
> アドレスバーに直接打ち込まない限りアクセスされないと思ったので

なるほど〜
