### ISSUE TITLE
OC用のサイトを作成

### ISSUE THREAD

**Issue by yuki-js** [tsukuba-shinkan/shinkan-next#8]
### TODO
- [x] ブランチを切る
  - [x] ワークフローも分ける
- [x] ディレクトリわける
- [x] 画像を差し替え
- [x] ようこそ画像の下にスロットはやして文言入れる

### 備考
データソースは一緒。
基本的には新歓の情報と一緒だが、OC用に編集するのも認める。ただしOC用に分ける仕組みを用意するものではない。

**Comment by yuki-js** [comment]
文言データ決めよう

**Comment by AsagaKosho** [comment]
OC用でお知らせの表示を消す

**Comment by yuki-js** [comment]
完了!
